# Generated by Django 6.0.3 on 2026-03-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Турдун аталышы')),
                ('price', models.IntegerField(verbose_name='Баасы (сом)')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Негизги сүрөт')),
                ('description', models.TextField(verbose_name='Тур жөнүндө маалымат')),
                ('duration', models.CharField(max_length=100, verbose_name='Мөөнөтү (мис: 3 күн)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Турлар',
            },
        ),
    ]
