# Generated by Django 6.0.3 on 2026-03-15 12:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_options_alter_tour_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('mountain', 'Тоо турлары'), ('horse', 'Атчан жүрүү'), ('vip', 'VIP Экспедиция')], default='mountain', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='tour',
            name='map_embed',
            field=models.TextField(blank=True, null=True, verbose_name='Карта (iframe)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Сүрөттөмөсү'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='Мөөнөтү'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Башкы сүрөт'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(verbose_name='Баасы (сом)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Турдун аталышы'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сүрөт маалыматы'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Кошумча сүрөт'),
        ),
    ]
