# Generated by Django 6.0.3 on 2026-03-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_category_tour_map_embed_alter_tour_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Турлар'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'verbose_name': 'Турдун сүрөтү', 'verbose_name_plural': 'Турдун сүрөттөрү'},
        ),
        migrations.AddField(
            model_name='tour',
            name='month',
            field=models.CharField(blank=True, choices=[('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь')], max_length=20, null=True, verbose_name='Кайсы айга таандык?'),
        ),
    ]
