# Generated by Django 6.0.3 on 2026-03-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tour_options_alter_tourimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.TextField(blank=True, help_text='Ар бир кызматты жаңы саптан жазыңыз', null=True, verbose_name='Баага эмнелер кирет?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included',
            field=models.TextField(blank=True, help_text='Ар бир пунктту жаңы саптан жазыңыз', null=True, verbose_name='Баага эмнелер кирбейт?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='program',
            field=models.TextField(blank=True, help_text='Ар бир күндү жаңы саптан жазыңыз (мисалы: 1-күн: Тосуп алуу)', null=True, verbose_name='Турдун программасы'),
        ),
    ]
